- id: '1695473497631'
  alias: Solcast update
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  - platform: time
    at: '12:00:00'
  - platform: time
    at: 04:00:00
  - platform: time
    at: 01:50:00
  - platform: time
    at: 04:00:00
  - platform: time
    at: 09:00:00
  - platform: time
    at: '15:00:00'
  - platform: time
    at: '18:00:00'
  condition: []
  action:
  - service: solcast_solar.update_forecasts
    data: {}
  mode: single
